### ISSUE TITLE
Can open the pdf file

### ISSUE THREAD

**Issue by PKDmeDEV** [caronchen/obsidian-calibre-plugin#13]
Hi, 

I can connect to Calibre and all bookcovers shows up fine. But I CAN'T open and read the pdfs. Nothing happens when I click the "Download" button.

Regards

**Comment by PKDmeDEV** [comment]
Sorry for the typo in title, it was supposed to be "Can't open/read/download the pdf file"

**Comment by b-nirlo** [comment]
I temporary sorted it out by modifying [Your Vault]/.obsidian/plugins/obsidian-calibre-plugin/**main.js** (might be overriden at next update)
Line 385, add allow-popups to the list (hint given by the Obdsidian console, ctrl+shift I)

**Before**
```javascript
iframe.setAttribute("sandbox", "allow-forms allow-presentation allow-same-origin allow-scripts allow-modals");
``` 
**Before**
```javascript
iframe.setAttribute("sandbox", "allow-forms allow-presentation allow-same-origin allow-scripts allow-modals allow-popups");
```

**Comment by PKDmeDEV** [comment]
Also the Download doesn't work yet.

**Comment by b-nirlo** [comment]
Just add "allow-downloads" next to "alow-popups". It works for me.

As regards selecting the application to open the PDF, keep in mind that what is framed in Obsidian is the page as it is generated by Calibre web server. So you'll get no more than what is designed there (behavior on click, layout, etc.)

The tiny alteration done on line 385 is just a set of instructions to "let" the framed page "talk" to its parent (Obsidian) and allow to do things (like open a browser, or download a file, etc.)

Remark: the above are just code tricks I did on my own. I'm not related to the author of the Obsidian plugin who I thank for his job.

**Comment by piyushdongre-dot-com** [comment]
After the update.
- Read option takes me to Chrome browser.
- Download option opens File explorer download.

**Comment by Freddd13** [comment]
> After the update. 更新之后。
> 
> * Read option takes me to Chrome browser.读取选项将我带到Chrome浏览器。
> * Download option opens File explorer download.下载选项打开文件资源管理器下载。

@PKDmeDEV Same here. How to read directly in obsidian? Have you solved that?
