### ISSUE TITLE
No main.js

### ISSUE THREAD

**Issue by fabiosirna** [caronchen/obsidian-calibre-plugin#2]
I'm trying to install the plugin manually following the instruction provided but there is not main.js in the zip I downloaded from github. Inside source there is main.ts but even if I rename it I got an error (Failed to load plugin obsidian-calibre-plugin).

I also tried to copy the full folder in my vault but I got the same issue.

**Comment by caronchen** [comment]
> I'm trying to install the plugin manually following the instruction provided but there is not main.js in the zip I downloaded from github. Inside source there is main.ts but even if I rename it I got an error (Failed to load plugin obsidian-calibre-plugin).
> 
> I also tried to copy the full folder in my vault but I got the same issue.

https://github.com/caronchen/obsidian-calibre-plugin/releases

**Comment by fabiosirna** [comment]
Thanks :)
