### ISSUE TITLE
plugin iframe is not taking the full height of the obsidian window

### ISSUE THREAD

**Issue by fabiosirna** [caronchen/obsidian-calibre-plugin#3]
I'm trying the plugin and as you can see from this screenshot, the iframe's plugin is not covering the fulle height of the window:

![image](https://user-images.githubusercontent.com/2249234/143771602-5f2a7213-5ee2-418f-a96d-78ec13b191d3.png)

is there a way to fix it?

**Comment by caronchen** [comment]
Fixed in version 1.0.2.
