### ISSUE TITLE
Issue: Cannot access calibre library from plugin

### ISSUE THREAD

**Issue by profucius** [caronchen/obsidian-calibre-plugin#4]
Obsidian version: 0.12.19
Calibre version: 5.33.2

I am trying to setup your plugin in my fresh Obsidian installation. I am following your provided steps, I activate the Content Server within Calibre, then open the Calibre tab within Obsidian, and then get this error:

`Failed to communicate with "/interface-data/init?1638909054161", with status: [400 (error)] Bad Request`
`Failed to parse header line`

I am able to access the same URL within a web browser just fine, that asks me to choose the calibre library. But Obsidian just will not access it. I tried disabling my firewall, no change. Any ideas?

In Obsidian:
![image](https://user-images.githubusercontent.com/18254607/145102112-97351a22-ac70-4c8d-a493-8d50ccd03d6d.png)

In Firefox:
![image](https://user-images.githubusercontent.com/18254607/145102203-603b8cb5-17ae-48c6-8755-e114b7bbae0a.png)

**Comment by profucius** [comment]
This plugin wouldn't by chance be using Edge or Internet Explorer to access, would it? I have those disabled as an administrator on my PC, perhaps that may explain it? If so, is there a workaround?

**Comment by caronchen** [comment]
Obsidian embedded Chromium.

**Comment by profucius** [comment]
What is causing this issue then?

**Comment by osman1963** [comment]
Found a solution :)
After starting the Calibre server, click on connect/share again
You'll see the actual address the server is conneced too, something like 19x.xxx.x.x :8080 (I guess this is the adress to connect to from the internet, not the local host? Is there a probelm connecting to it? I'm not sure, but it works anyways )
Copy this adress exactly to the "Server Adress" in the plugin settings
and.. voila.. it works
If this is not a safe way please let me know. Othewise, cheers and enjoy :)

**Comment by profucius** [comment]
Yes I just verified this method worked. Thank you for the workaround.

**Comment by neKmaI** [comment]
is there other ways to fix the problem :((
